import ButtonLoading from './ButtonLoading';
import ButtonDelete from './ButtonDelete';
import ButtonPost from './ButtonPost';
import ButtonAdd from './ButtonAdd';
import DropdownMenu from './DropdownMenu';
import FieldSelect from './FieldSelect';
import FieldDate from './FieldDate';
import Calendar from './Calendar';
import Table from './Table';
import FileUpload from './FileUpload';
import Tabs from './Tabs';
import RadioButtons from './RadioButtons';

ButtonLoading.init();
ButtonDelete.init();
ButtonPost.init();
ButtonAdd.init();
DropdownMenu.init();
FieldSelect.init();
FieldDate.init();
Calendar.init();
Table.init();
FileUpload.init();
Tabs.init();
RadioButtons.init();